# Preinstall Infrastructure Configuration
# This chart creates StorageClass and PersistentVolumes for NASA Data Hub

# StorageClass Configuration
storageClass:
  enabled: true
  name: "{{ .Values.global.storage.class }}"
  isDefault: true
  provisioner: "kubernetes.io/no-provisioner"
  volumeBindingMode: "WaitForFirstConsumer"

# PersistentVolumes Configuration
persistentVolumes:
  enabled: true
  
  # MinIO PersistentVolume
  minio:
    enabled: true
    name: "nasa-data-hub-minio-pv"
    size: "{{ .Values.global.storage.minioSize }}"
    path: "/tmp/nasa-data-hub-minio"
    
  # Vertica PersistentVolumes
  vertica:
    enabled: true
    count: 1  # Number of PVs to create (integer)
    size: "{{ .Values.global.storage.verticaSize }}"
    basePath: "/tmp/nasa-data-hub-vertica"
    baseName: "nasa-data-hub-vertica-pv"
    
  # Metabase Data PersistentVolume
  metabaseData:
    enabled: true
    name: "nasa-data-hub-metabase-data-pv"
    size: "{{ .Values.global.storage.metabaseSize }}"
    path: "/tmp/nasa-data-hub-metabase-data"

# Directory Creation
directories:
  enabled: true
  basePath: "/tmp"
  permissions: "777"

# MinIO Configuration (for VerticaDB secret)
minio:
  auth:
    rootUser: "admin"
    rootPassword: "nasa-data-hub-2025"
