{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metabase.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: visualization
  template:
    metadata:
      labels:
        {{- include "metabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: visualization
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-vertica
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z nasa-data-hub-vertica-nasa-data-hub-vertica 5433; do echo waiting for vertica; sleep 2; done;']
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 50m
      containers:
      - name: metabase
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: MB_ENCRYPTION_SECRET_KEY
          value: {{ .Values.config.encryptionSecretKey | quote }}
        - name: MB_DB_TYPE
          value: {{ .Values.config.databaseType | quote }}
        - name: MB_DB_HOST
          value: {{ .Values.config.databaseHost | quote }}
        - name: MB_DB_PORT
          value: {{ .Values.config.databasePort | quote }}
        - name: MB_DB_DBNAME
          value: {{ .Values.config.databaseName | quote }}
        - name: MB_DB_USER
          value: {{ .Values.config.databaseUser | quote }}
        - name: MB_DB_PASS
          value: {{ .Values.config.databasePassword | quote }}
        - name: JAVA_OPTS
          value: "-Xmx1536m -Xms512m"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "metabase.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
