apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metabase.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
