apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: visualization
