{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "minio.serviceAccountName" . }}-job-checker
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: minio
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "minio.serviceAccountName" . }}-job-checker
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "minio.serviceAccountName" . }}-job-checker
subjects:
- kind: ServiceAccount
  name: {{ template "minio.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}

