apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vdb-op.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
{{- end }}
