apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ include "vdb-op.name" . }}
    vertica.com/svc-type: webhook
  name: {{ include "vdb-op.name" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: {{ include "vdb-op.name" . }}
